name: inception

services:
  nginx:
    restart: always

    image: inception/proxy
    build: ./requirements/nginx/
    ports:
      - "8080:80" # MUST BE CHANGED TO 443 LATER ON

    #secrets:
    #  - ssl_cert
    configs:
      - source: nginx-config
        target: /etc/nginx/sites-available/inception

configs:
  nginx-config:
    file: ./requirements/nginx/inception.conf
