name: inception

services:
  nginx:
    restart: always
    pull_policy: never

    image: nginx:inception
    build: ./requirements/nginx/
    volumes:
      - static-content:/var/www/html
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy

    configs:
      - source: nginx-config
        target: /etc/nginx/sites-available/inception
    secrets:
      - nginx-ssl-cert
      - nginx-ssl-cert-key

  wordpress:
    restart: always
    pull_policy: never

    image: wordpress:inception
    build: ./requirements/wordpress/
    volumes:
      - static-content:/var/www/html
    expose:
      - "9000"
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "cgi-fcgi -bind -connect 127.0.0.1:9000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

    configs:
      - source: nginx-config
        target: /etc/nginx/sites-available/inception
    environment:
      DOMAIN_NAME: jamar.42.fr
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_USER_PASSWORD_FILE: /run/secrets/mariadb-user-pw
      WP_ADMIN_USER: mamiya
      WP_ADMIN_EMAIL: jamar@student.42.fr
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wordpress-admin-pw
      WP_USER: pentax
      WP_USER_EMAIL: jamar+1@student.42.fr
      WP_USER_PASSWORD_FILE: /run/secrets/wordpress-user-pw
    secrets:
      - mariadb-user-pw
      - wordpress-admin-pw
      - wordpress-user-pw

  mariadb:
    restart: always
    pull_policy: never

    image: mariadb:inception
    build: ./requirements/mariadb/
    volumes:
      - database-store:/var/lib/mysql
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "--silent", "-u$$MARIADB_USER", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

    environment:
      MARIADB_ROOT_HOST: localhost
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_USER_PASSWORD_FILE: /run/secrets/mariadb-user-pw
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mariadb-root-pw
    secrets:
      - mariadb-user-pw
      - mariadb-root-pw

configs:
  nginx-config:
    file: ./requirements/nginx/inception.conf

volumes:
  static-content:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/wordpress'
  database-store:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/mariadb'

secrets:
  nginx-ssl-cert:
    file: ../secrets/jamar.42.fr.crt
  nginx-ssl-cert-key:
    file: ../secrets/jamar.42.fr.key
  mariadb-user-pw:
    file: ../secrets/mariadb_user_password
  mariadb-root-pw:
    file: ../secrets/mariadb_root_password
  wordpress-admin-pw:
    file: ../secrets/wordpress_admin_password
  wordpress-user-pw:
    file: ../secrets/wordpress_user_password

networks:
  inception:
    driver: bridge
